version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  json-server:
    build:
      context: ./
      dockerfile: Dockerfile.json-server
    ports:
      - "3000:3000"