FROM node:18
RUN mkdir /data
WORKDIR /data
COPY db.json /data/db.json
RUN npm install -g json-server@0.17.4
EXPOSE 3000
CMD ["json-server", "--watch", "db.json", "--host", "0.0.0.0", "--port", "3000"]
